import random
def createbankaccount():
      nam=input("Enter Your name : ")
      dob=int(input("Enter Your date of birth(ddmmyyyy) : "))
      ad=int(input("Enter your AADHAR NUMBER : "))
      pn=input("Enter Your PAN NUMBER : ")
      pas=input("Enter an alphanumeric password (greater than 8 words and can include special character too) : ")
      ac=random(10,9999999999)
      cif=random(11,33333333333)
      print("your account number is ", c)
      print("your cif number is ", cif)
      print("please note the account number and cif number for future reference !!!!!!!!")
def account_deletion():
      dac=input("PLEASE ENTRE YOUR ACCOUNT NUMBER ")
      dcif=input
      dad=input
      dcif=input
      print("YOUR ACCOUNT DETAILS ARE ")
      print(ac,cif,nam,dob,pn,ad)
      con=("Are you sure to delete your account (y/n) : ")
      if con==y or con==Y:
            #drop database
def money_transfer():
      mtac=int(input("Enter your account number : "))
      mtcif=input("Enter your cif number : ")
      #check the bank balance of owner bank account and its details for the same and if it is good then else ask to enter the account detailsagain or exit
      balo=balance of owner account through database
      mtm=int(input("Enter the amount you want to transfer : "))
      if balo>=mtm:
            mtbac=int(input("Enter beneficary account number : "))
            mtcif=input("Enter the cif of b account : ")
            #check for details of benificary
            if details are good:
                  mtpas=input("Enter your password : ")
                  #check for passwords
                  if password is good:
                        print("You have transferred" ,mtm, "to#beneficary deatils from database" )
                        print("thankyou for using money transfer")
                        #add the given amount to the benificary account in through insertinto database command and generate a transction no. using random finc and print it
      else:
            print("NoT enough balance")
def login_sysyem ():
      dbac=int(input("Enter account number : ")) 
      lsac=int(input("Enter your A/C : "))
      if lsac==dbac:
            passadhrlogin()
      else:
            ch=input("wrong a/c!!  WOULD YOU LIKE TO TRY AGAIN (y/n) : ")
            if ch=="y" or ch=="Y":
                  login_sysyem()
            else:
                print("OUT OF LOGIN SYSTEM")

def passadhrlogin():
            #FROM DATABASE          dbpas=input("Enter your password : ")
            #FROM DATABASE          dbad=int(input("Enter your addharcard no. : "))
            lsad=int(input("Enter your addharcard no. : "))
            lsps=input("Enter your password : ")
            if lsps==dbpas and lsad==dbad:
                  print("WELCOME TO SBI")
            else:
                  ch=input("wrong password or addhar number!!  WOULD YOU LIKE TO TRY AGAIN (y/n) : ")
                  if ch=='y' or ch=="Y":
                        passadhrlogin()
                  else:
                        print("OUT OF LOGIN WINDOW")
passadhrlogin()
def deposit_sys():
      #for cashier
      #dbac=int(input("Enter account number : ")) FROM DATA BASE
      #dbcif=(input("Enter account cif : ")) FROM DATABASE
      #dbab=int(input("Enter account balance : ")) FROM DATABASE
      dsac=int(input("Enter account number : "))
      dscif=input("Enter the IFSC CODE : ")
      if dsac==dbac and dscif==dbcif:
               DA=float(input("ENTER THE AMOUNT TO BE DEPOSITED"))
               ch=input("ARE YoU SURE!!!!!  (Y/N) and to exit press any key : ")
               if ch=="y" or ch=="Y":
                     print ("deposited amount is", DA ," account balance is ", dbab+DA ,"and your transaction reference number is","#number generated by randomfunc")
               elif ch=="n" or ch=="N":
                     deposit_sys()
               else:
                ech=input("DO YOUWANT TOO EXIT(Y?N) :")
                if ech=="y" or ech=="Y":
                    ( "exited from ds")
                else:
                    deposit_sys()
      else:
        print("Entery doesnt match")

deposit_sys()

            
            
def withdraw_sys():
      #FROM DATABASE          dbac=int(input("Enter account number : "))
      #FROM DATABASE          dbcif=input("Enter account cif : ")
      #FROM DATABASE          blow=float(input("Enter account balance : "))
      #FROM DATABASE          dbpas=input("Enter password : ")
      wsac=int(input("Enter account number : "))
      wscif=input("Enter the IFSC CODE : ")
      if wsac==dbac and wscif==dbcif:
            WA=float(input("ENTER THE AMOUNT TO BE withdrawn"))
            if blow>=WA:
                  ch="y"
                  while ch=="y":
                        wspas=input("Enter your password : ")
                        #check for passwords makkhan
                        if wspas == dbpas :
                              print("You have withdrawn", WA , "and the remaning balance is ",blow-WA)
                              print("thankyou for using money withdrawing system")
                              ch="n"
                        else:
                              ch=input("wrong password !!  WOULD YOU LIKE TO TRY AGAIN (y/n) : ")
                              if ch=='y' or ch=="Y":
                                    ch='y'
                              else :
                                    print("Exited from withdrawnsys")
                                    ch="n"#makkahan
            else:
                print("insufficient balnce")
      else:
        ch=input("Wrong details entered!!!!  WOULD YOU LIKE TO TRY AGAIN(Y/N)")
        if ch=='y' or ch=="Y":
            withdraw_sys()
        else:
            print("Exited from withdrawing system")

withdraw_sys()

                  
                        
                  
      
      
                                   
               
            
               
      
                        
            
      
     
      
            
                        
                  
      
      
      
